/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasAreaIdRouteImport } from './routes/areas.$areaId'
import { Route as AreasAreaIdWallsWallIdRouteImport } from './routes/areas.$areaId.walls.$wallId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaIdRoute = AreasAreaIdRouteImport.update({
  id: '/areas/$areaId',
  path: '/areas/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaIdWallsWallIdRoute = AreasAreaIdWallsWallIdRouteImport.update({
  id: '/walls/$wallId',
  path: '/walls/$wallId',
  getParentRoute: () => AreasAreaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas/$areaId': typeof AreasAreaIdRouteWithChildren
  '/areas/$areaId/walls/$wallId': typeof AreasAreaIdWallsWallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas/$areaId': typeof AreasAreaIdRouteWithChildren
  '/areas/$areaId/walls/$wallId': typeof AreasAreaIdWallsWallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas/$areaId': typeof AreasAreaIdRouteWithChildren
  '/areas/$areaId/walls/$wallId': typeof AreasAreaIdWallsWallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/areas/$areaId' | '/areas/$areaId/walls/$wallId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas/$areaId' | '/areas/$areaId/walls/$wallId'
  id: '__root__' | '/' | '/areas/$areaId' | '/areas/$areaId/walls/$wallId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasAreaIdRoute: typeof AreasAreaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaId': {
      id: '/areas/$areaId'
      path: '/areas/$areaId'
      fullPath: '/areas/$areaId'
      preLoaderRoute: typeof AreasAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaId/walls/$wallId': {
      id: '/areas/$areaId/walls/$wallId'
      path: '/walls/$wallId'
      fullPath: '/areas/$areaId/walls/$wallId'
      preLoaderRoute: typeof AreasAreaIdWallsWallIdRouteImport
      parentRoute: typeof AreasAreaIdRoute
    }
  }
}

interface AreasAreaIdRouteChildren {
  AreasAreaIdWallsWallIdRoute: typeof AreasAreaIdWallsWallIdRoute
}

const AreasAreaIdRouteChildren: AreasAreaIdRouteChildren = {
  AreasAreaIdWallsWallIdRoute: AreasAreaIdWallsWallIdRoute,
}

const AreasAreaIdRouteWithChildren = AreasAreaIdRoute._addFileChildren(
  AreasAreaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasAreaIdRoute: AreasAreaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
