/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicksRouteImport } from './routes/ticks'
import { Route as MeRouteImport } from './routes/me'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasAreaIdRouteImport } from './routes/areas.$areaId'
import { Route as AreasAreaIdWallsWallIdRouteImport } from './routes/areas.$areaId.walls.$wallId'
import { Route as AreasAreaIdWallsWallIdRoutesRouteIdRouteImport } from './routes/areas.$areaId.walls.$wallId.routes.$routeId'

const TicksRoute = TicksRouteImport.update({
  id: '/ticks',
  path: '/ticks',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaIdRoute = AreasAreaIdRouteImport.update({
  id: '/areas/$areaId',
  path: '/areas/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaIdWallsWallIdRoute = AreasAreaIdWallsWallIdRouteImport.update({
  id: '/walls/$wallId',
  path: '/walls/$wallId',
  getParentRoute: () => AreasAreaIdRoute,
} as any)
const AreasAreaIdWallsWallIdRoutesRouteIdRoute =
  AreasAreaIdWallsWallIdRoutesRouteIdRouteImport.update({
    id: '/routes/$routeId',
    path: '/routes/$routeId',
    getParentRoute: () => AreasAreaIdWallsWallIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/me': typeof MeRoute
  '/ticks': typeof TicksRoute
  '/areas/$areaId': typeof AreasAreaIdRouteWithChildren
  '/areas/$areaId/walls/$wallId': typeof AreasAreaIdWallsWallIdRouteWithChildren
  '/areas/$areaId/walls/$wallId/routes/$routeId': typeof AreasAreaIdWallsWallIdRoutesRouteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/me': typeof MeRoute
  '/ticks': typeof TicksRoute
  '/areas/$areaId': typeof AreasAreaIdRouteWithChildren
  '/areas/$areaId/walls/$wallId': typeof AreasAreaIdWallsWallIdRouteWithChildren
  '/areas/$areaId/walls/$wallId/routes/$routeId': typeof AreasAreaIdWallsWallIdRoutesRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/me': typeof MeRoute
  '/ticks': typeof TicksRoute
  '/areas/$areaId': typeof AreasAreaIdRouteWithChildren
  '/areas/$areaId/walls/$wallId': typeof AreasAreaIdWallsWallIdRouteWithChildren
  '/areas/$areaId/walls/$wallId/routes/$routeId': typeof AreasAreaIdWallsWallIdRoutesRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/me'
    | '/ticks'
    | '/areas/$areaId'
    | '/areas/$areaId/walls/$wallId'
    | '/areas/$areaId/walls/$wallId/routes/$routeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/me'
    | '/ticks'
    | '/areas/$areaId'
    | '/areas/$areaId/walls/$wallId'
    | '/areas/$areaId/walls/$wallId/routes/$routeId'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/me'
    | '/ticks'
    | '/areas/$areaId'
    | '/areas/$areaId/walls/$wallId'
    | '/areas/$areaId/walls/$wallId/routes/$routeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  MeRoute: typeof MeRoute
  TicksRoute: typeof TicksRoute
  AreasAreaIdRoute: typeof AreasAreaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticks': {
      id: '/ticks'
      path: '/ticks'
      fullPath: '/ticks'
      preLoaderRoute: typeof TicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaId': {
      id: '/areas/$areaId'
      path: '/areas/$areaId'
      fullPath: '/areas/$areaId'
      preLoaderRoute: typeof AreasAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaId/walls/$wallId': {
      id: '/areas/$areaId/walls/$wallId'
      path: '/walls/$wallId'
      fullPath: '/areas/$areaId/walls/$wallId'
      preLoaderRoute: typeof AreasAreaIdWallsWallIdRouteImport
      parentRoute: typeof AreasAreaIdRoute
    }
    '/areas/$areaId/walls/$wallId/routes/$routeId': {
      id: '/areas/$areaId/walls/$wallId/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/areas/$areaId/walls/$wallId/routes/$routeId'
      preLoaderRoute: typeof AreasAreaIdWallsWallIdRoutesRouteIdRouteImport
      parentRoute: typeof AreasAreaIdWallsWallIdRoute
    }
  }
}

interface AreasAreaIdWallsWallIdRouteChildren {
  AreasAreaIdWallsWallIdRoutesRouteIdRoute: typeof AreasAreaIdWallsWallIdRoutesRouteIdRoute
}

const AreasAreaIdWallsWallIdRouteChildren: AreasAreaIdWallsWallIdRouteChildren =
  {
    AreasAreaIdWallsWallIdRoutesRouteIdRoute:
      AreasAreaIdWallsWallIdRoutesRouteIdRoute,
  }

const AreasAreaIdWallsWallIdRouteWithChildren =
  AreasAreaIdWallsWallIdRoute._addFileChildren(
    AreasAreaIdWallsWallIdRouteChildren,
  )

interface AreasAreaIdRouteChildren {
  AreasAreaIdWallsWallIdRoute: typeof AreasAreaIdWallsWallIdRouteWithChildren
}

const AreasAreaIdRouteChildren: AreasAreaIdRouteChildren = {
  AreasAreaIdWallsWallIdRoute: AreasAreaIdWallsWallIdRouteWithChildren,
}

const AreasAreaIdRouteWithChildren = AreasAreaIdRoute._addFileChildren(
  AreasAreaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  MeRoute: MeRoute,
  TicksRoute: TicksRoute,
  AreasAreaIdRoute: AreasAreaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
